// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMIukCR6T38SciLFFfLUwnfhxVKxtpdms',
    appId: '1:131583608907:web:e421b6000549cd15d8a5ce',
    messagingSenderId: '131583608907',
    projectId: 'lagoo-c36db',
    authDomain: 'lagoo-c36db.firebaseapp.com',
    storageBucket: 'lagoo-c36db.firebasestorage.app',
    measurementId: 'G-SS3B39L0K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VTBmHCUoXmeVg0Joo9C7sXrkVVOAjTU',
    appId: '1:131583608907:android:39915d2537e6bf35d8a5ce',
    messagingSenderId: '131583608907',
    projectId: 'lagoo-c36db',
    storageBucket: 'lagoo-c36db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqPhyesr2qk8Oj6f-gPQT7aSG9iPzUsXo',
    appId: '1:131583608907:ios:5ba93a2f6f63db50d8a5ce',
    messagingSenderId: '131583608907',
    projectId: 'lagoo-c36db',
    storageBucket: 'lagoo-c36db.firebasestorage.app',
    iosBundleId: 'com.example.lowgosApp',
  );
}
